name: cupertino_ffi
version: 0.1.5
description:
  A large number of APIs by Apple made available with 'dart:ffi'. Contains helpers for using
  any Objective-C library.
homepage: https://github.com/dart-interop/cupertino_ffi
author: terrier989 <terrier989@gmail.com>

environment:
  sdk: '>=2.5.0 <3.0.0'

dependencies:
  ffi: ^0.1.1
  meta: ^1.1.0

dev_dependencies:
  ffi_tool: any
  pedantic: ^1.8.0
  test: ^1.6.0